services:
  george_mysql:
    image: mysql:8.4
    container_name: george_mysql
    hostname: george_mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=george
      - MYSQL_USER=george
      - MYSQL_PASSWORD=george
      - TZ=Europe/Rome
    volumes:
      - george_mysql_volume:/var/lib/mysql
  george_redis:
    image: redis:7.4-alpine
    container_name: george_redis
    hostname: george_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
volumes:
  george_mysql_volume:
